# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "Github-Asana bridge"

description: "Action to manage an Asana Task based on activity in Github"

inputs:
  ONLY_REACT_TO:
    description: >
      What user set to react to. One of: `specified-users | all`
      where `all` is anyone with access to raise an Issue, while
      `specified-users` is an allowlist of usernames, passed as ACTOR_ALLOWLIST
    required: false
    default: repo-org
  ACTOR_ALLOWLIST:
    description: >
      Comma-separated string of login names/usernames who may trigger
      mirroring to Asana - see ONLY_REACT_TO
    required: false
  ASANA_PROJECT:
    description: The Asana project two which you are bridging.
    required: true
  ASANA_PAT:
    description: The access token required to manipulate Asana.
    required: true
  REPO_TOKEN:
    description: >
      A token with appropriate scope to inspect the repo - see README
    required: true
  TAG:
    description: >
      The specific version of the project to check out when running the sync
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: "mozmeao/asana-github-bridge"
        ref: ${{ inputs.TAG }}
        path: bridger
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: "Install Python dependencies"
      shell: bash
      run: pip install -r bridger/requirements.txt
    - name: "Create/Update Asana task"
      shell: bash
      run: bridger/bin/manage_asana_task.py
      env:
        ACTOR: ${{ github.actor }}
        ASANA_PAT: ${{ inputs.ASANA_PAT }}
        ASANA_PROJECT: ${{ inputs.ASANA_PROJECT }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_URL: ${{ github.event.issue.html_url }}
        REPO: ${{ github.repository }}
        REPO_TOKEN: ${{ inputs.REPO_TOKEN }}
        ONLY_REACT_TO: ${{ inputs.ONLY_REACT_TO }}
        ACTOR_ALLOWLIST: ${{ inputs.ACTOR_ALLOWLIST }}
