# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "Github-Asana bridge"

description: "Action to manage an Asana Task based on activity in Github"

inputs:
  only-react-to:
    description: >
      What user set to react to. One of: `repo-team | repo-org | all`
      where `all` is anyone with access to raise an Issue, `repo-team`
      has team-level access to the caller repo and `repo-org` is someone
      with org-level _membership_ for the org the caller repo is in
    required: false
    default: repo-org
  ASANA_PROJECT:
    description: The Asana project two which you are bridging.
    required: true
  ASANA_PAT:
    description: The access token required to manipulate Asana.
    required: true
  REPO_TOKEN:
    description: >
      A token with appropriate scope to inspect the repo - see README
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: "Install Python dependencies"
      shell: bash
      run: pip install -r requirements.txt
    - name: "Create/Update Asana task"
      shell: bash
      run: bin/manage_asana_task.py
      env:
        ACTOR: ${{ github.actor }}
        ASANA_PAT: ${{ inputs.ASANA_PAT }}
        ASANA_PROJECT: ${{ inputs.ASANA_PROJECT }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_URL: ${{ github.event.issue.html_url }}
        REPO: ${{ github.repository }}
        REPO_TOKEN: ${{ inputs.REPO_TOKEN }}
        ONLY_REACT_TO: ${{ inputs.only-react-to }}
