# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Used to test the Asana bridge, and also a reference implementation of sorts,
# though note that this uses the action locally, but you'd have to load it
# from the repo. See the README

name: "Github-Asana bridge: development"

on:
  issues:
    types:
      - opened
      # - edited # TODO: add support for me
      # - closed # TODO: add support for me

jobs:
  handle_issue:
    name: "Trigger following GH Issue save"
    uses: ./.github/workflows/issue_handler.yaml
    with:
      only-react-to: repo-org
    secrets:
      ASANA_PAT: ${{ secrets.ASANA_PAT }}
      ASANA_PROJECT: ${{ secrets.ASANA_PROJECT }}
      REPO_TOKEN: ${{ secrets.ASANA_GITHUB_BRIDGE_TOKEN }}
