# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: "Github-Asana bridge"

on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string
      issue-url:
        description: The URL of the Github Issue that triggered this workflow.
        required: true
        type: string
      issue-title:
        description: The title of the Github Issue that triggered this workflow.
        required: true
        type: string
      issue-body:
        description: The body of the Github Issue that triggered this workflow.
        required: true
        type: string
      issue-timestamp:
        description: The last-updated timestamp of the Github Issue that triggered this workflow.
        required: true
        type: string
      only-react-to:
        description: >
          What user set to react to. One of: `repo-team | repo-org | all`
          where `all` is anyone with access to raise an Issue, `repo-team`
          has team-level access to the caller repo and `repo-org` is someone
          with org-level _membership_ for the org the caller repo is in
        required: false
        default: repo-org
        type: string
    secrets:
      ASANA_PROJECT:
        description: The Asana project two which you are bridging.
        required: true
      ASANA_PAT:
        description: The access token required to manipulate Asana.
        required: true
      REPO_TOKEN:
        description: >
          A token with appropriate scope to inspect the repo - see README
        required: true

jobs:
  manage_asana_issue:
    name: "Trigger Github-Asana bridge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install Python dependencies"
        run: pip install -r requirements.txt
      - name: "Create/Update Asana task"
        run: bin/manage_asana_task.py
        env:
          ACTOR: ${{ inputs.actor }}
          ASANA_PAT: ${{ secrets.ASANA_PAT }}
          ASANA_PROJECT: ${{ secrets.ASANA_PROJECT }}
          ISSUE_BODY: ${{ inputs.issue-body }}
          ISSUE_TIMESTAMP: ${{ inputs.issue-timestamp }}
          ISSUE_TITLE: ${{ inputs.issue-title }}
          ISSUE_URL: ${{ inputs.issue-url }}
          REPO: ${{ github.repository }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          ONLY_REACT_TO: ${{ inputs.only-react-to }}
